---
metasheet: metasheet.csv
ref: ref.yaml
assembly: 'rheMac8'

## Is your library stranded? options are [true, false]
stranded: false
# Possible values are [ff-firststrand, ff-secondstrand, ff-unstranded, fr-firststrand, fr-secondstrand, fr-unstranded (default), transfrags]
library_type: 'fr-unstranded'

##PIPELINE CONTROL, whether perform these analysis
## mapping and counting
bam2bw: false
align: false
star_counts: false
cuff_counts: false

## filter fpkm table, sample QC
# If this flag is on, you must have a metasheet column called batch with at least 2 samples per batch
batch_effect_removal: false
# Filters out "SNO" and "MIR" RNA, options are [true,false]
filter_mirna: false
cuff_filter_counts: false
cluster: true

## DEG
deg: true

## go, kegg and gsea 
go_analysis: true
kegg_analysis: true
gsea_analysis: true




##PARAMS, how to perform these analysis
## PCA and Heatmap params, filter low expressed genes in fpkm table params
RPKM_threshold: 1.0
min_num_samples_expressing_at_threshold: 1
## Number of genes to be represented in the Sample-Sample, Sample-Feature, and PCA plots
numgenes_plots: "1000,2000,50000"
## Plotting param for Sample-Feature Heatmap. Number represents number of kmeans in heatmap, 0 will output a hierarchical clustering heatmap, finally, a list of numbers "0,2,4" will output all three heatmaps in the same pdf (NOTE: be sure to include the "quotes" ONLY when giving a list!  Do not give quotes when it's just a single number)
num_kmeans_clust: 0


## adjpval for a gene to be considered differentially expressed and be included in GOterm analysis
goterm_adjpval_cutoff: "0.01,0.05"
## Number of GOterms in plot
numgoterms: 15
## Number of KEGG pathways in plot (note there is no cutoff herre because the KEGG module takes in full population statistics)
#numkeggpathways: 15
## Number of GSEA term in plot
#numgsea: 15
#Path to gene set enrichment db
#gsea_db: static/gsea/msigdb.v6.1.symbols.gmt



samples:
  10068A-CPi-RNA-lib:
    - data/10068A-CPi-RNA-lib/10068A-CPi-RNA-lib_R1.fq.gz
    - data/10068A-CPi-RNA-lib/10068A-CPi-RNA-lib_R2.fq.gz
  10068A-CPo-RNA-lib:
    - data/10068A-CPo-RNA-lib/10068A-CPo-RNA-lib_R1.fq.gz
    - data/10068A-CPo-RNA-lib/10068A-CPo-RNA-lib_R2.fq.gz
  10068A-ISVZ-RNA-lib:
    - data/10068A-ISVZ-RNA-lib/10068A-ISVZ-RNA-lib_R1.fq.gz
    - data/10068A-ISVZ-RNA-lib/10068A-ISVZ-RNA-lib_R2.fq.gz
  10068A-IZ-RNA-lib:
    - data/10068A-IZ-RNA-lib/10068A-IZ-RNA-lib_R1.fq.gz
    - data/10068A-IZ-RNA-lib/10068A-IZ-RNA-lib_R2.fq.gz
  10068A-MZ-RNA-lib:
    - data/10068A-MZ-RNA-lib/10068A-MZ-RNA-lib_R1.fq.gz
    - data/10068A-MZ-RNA-lib/10068A-MZ-RNA-lib_R2.fq.gz
  10068A-OSVZ-RNA-lib:
    - data/10068A-OSVZ-RNA-lib/10068A-OSVZ-RNA-lib_R1.fq.gz
    - data/10068A-OSVZ-RNA-lib/10068A-OSVZ-RNA-lib_R2.fq.gz
  10068A-SP-RNA-lib:
    - data/10068A-SP-RNA-lib/10068A-SP-RNA-lib_R1.fq.gz
    - data/10068A-SP-RNA-lib/10068A-SP-RNA-lib_R2.fq.gz
  10068A-VZ-RNA-lib:
    - data/10068A-VZ-RNA-lib/10068A-VZ-RNA-lib_R1.fq.gz
    - data/10068A-VZ-RNA-lib/10068A-VZ-RNA-lib_R2.fq.gz
